##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # keepalived
  keepalived:
    image: ${IMAGE_KEEPALIVED}
    container_name: "keepalived.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "keepalived.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    environment:
      - KEEPALIVED_INTERFACE=ens33
      - KEEPALIVED_PASSWORD=abcd1234
      - KEEPALIVED_PRIORITY=150
      - KEEPALIVED_ROUTER_ID=51
      - KEEPALIVED_UNICAST_PEERS="#PYTHON2BASH:['192.168.100.12','192.168.100.13','192.168.100.14']"
      - KEEPALIVED_VIRTUAL_IPS="#PYTHON2BASH:['192.168.100.250']"
      # KEEPALIVED_NOTIFY=/container/service/keepalived/assets/notify.sh
      # KEEPALIVED_COMMAND_LINE_ARGUMENTS=--log-detail --dump-conf
      # KEEPALIVED_STATE=MASTER or BACKUP
      - KEEPALIVED_STATE=MASTER
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/keepalived/conf/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro
    network_mode: "host"
    extra_hosts:
      - "keepalived.${PRODUCT_NAME}.${COMPANY_NAME}:${HOST_IP}"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW

