##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # keepalived
  keepalived:
    image: "${IMAGE_KEEPALIVED}"
    container_name: "keepalived.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "keepalived.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    env_file:
      - ./keepalived.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./volume/keepalived/conf/keepalived.conf:/etc/keepalived/keepalived.conf:ro
    network_mode: "host"
    extra_hosts:
      - "keepalived.${PRODUCT_NAME}.${COMPANY_NAME}:${HOST_IP}"
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BROADCAST
